name: Run Spam Detection
on:
  issues:
    types: [opened, edited]
  pull_request:
    types: [opened, edited]
  discussion_comment:
    types: [created, edited]

jobs:
  run_spam_detection:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run AutoHide Spam Comments
        uses: Sambhaji-Patil/spam-detection-action@v1.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          repo_owner: ${{ github.repository_owner }}
          repo_name: ${{ github.repository }}
