name: Spam Detection

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  discussion_comment:
    types: [created]  

jobs:
  detect-spam:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      discussions: write
      contents: read 

    steps:
      - uses: actions/checkout@v3  
      - name: Spam Detection
        uses: Sambhaji-Patil/AutoHide-Spam@v1.0 
