
name: Spam Detection
on:
  schedule:
    - cron: '0 */3 * * *'  
  workflow_dispatch: 

jobs:
  detect-spam:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      discussions: write
      contents: read 

    steps:
      - uses: actions/checkout@v3  

      - name: Restore Cache
        uses: actions/cache@v3
        with:
          path: .github/cache
          key: cursor-cache

      - name: Spam Detection
        uses: Sambhaji-Patil/Auto-Hide-Spam-Comments@v1.1 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CURSOR_FILE: .github/cache/last_cursor.txt

      - name: Save Cache
        uses: actions/cache@v3
        with:
          path: .github/cache
          key: cursor-cache
