name: Spam Detection

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  discussion_comment:
    types: [created]

permissions:
  issues: write
  pull-requests: write
  discussions: write
  contents: read

jobs:
  detect-spam:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # This is important for accessing repository files

      - name: Run Spam Detection
        uses: Sambhaji-Patil/hide-spam-comments@v1.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          repo_owner: ${{ github.repository_owner }}
          repo_name: ${{ github.repository }}
